name: Deploy to production

on:
  repository_dispatch:
    types: [swap-command]

jobs:
  deploy-prod:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SUBSCRIPTION_SECRET }}

    - uses: chrnorm/deployment-action@v1.2.0
      name: Create GitHub deployment
      id: deployment
      with:
        token: ${{github.token }}
        ref: ${{ github.event.client_payload.pull_request.head.sha }}
        environment: production

    - name: Swap staging to production
      run: |
        az webapp deployment slot swap --name popular-repos --resource-group pied-piper-inc --slot staging --target-slot production
        
    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: http://popular-repos.azurewebsites.net
        state: "success"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
    
    - name: Comment on success
      if: success()
      uses: peter-evans/create-or-update-comment@v1.4.1
      with:
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        reaction: hooray
        body: |
          Successfully deployed [PR-${{ github.event.client_payload.pull_request.number }}](https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }}) to [production](http://popular-repos.azurewebsites.net)

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        state: "failure"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      
    - name: Comment on failure
      if: failure()
      uses: peter-evans/create-or-update-comment@v1.4.1
      with:
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        reaction: eyes, confused
        body: |
          Failed to deploy #${{ github.event.client_payload.pull_request.number }} to production

          See https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }}
